using AzureStorageAutoBackup.Files;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AzureStorageAutoBackup.Tests.Stubs
{
    public class FakeFileReader : IFileReader
    {
        public Task<List<FileItem>> ReadAllFiles(List<string> basePath)
        {
            return Task.FromResult(GetFakeFiles().Select(x => FileItem.Create(x)).ToList());
        }

        public Stream OpenRead(string fileName)
        {
            var bytes = Encoding.UTF8.GetBytes($"Test file with checksum {fileName}");
            return new MemoryStream(bytes);
        }

        private IEnumerable<string> GetFakeFiles()
        {
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\AppConfiguration.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\AzureStorageAutoBackup.csproj";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\AzureStorageAutoBackup.sln";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\Program.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.deps.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.exe";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.pdb";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.runtimeconfig.dev.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.runtimeconfig.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\Microsoft.Extensions.DependencyInjection.Abstractions.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\Microsoft.Extensions.Options.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\Microsoft.Extensions.Primitives.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\MoreLinq.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\bin\\Debug\\net5.0\\ref\\AzureStorageAutoBackup.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\Files\\FilesBuilder.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\AzureStorageAutoBackup.csproj.nuget.dgspec.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\AzureStorageAutoBackup.csproj.nuget.g.props";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\AzureStorageAutoBackup.csproj.nuget.g.targets";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\project.assets.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\project.nuget.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\apphost.exe";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.AssemblyInfo.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.AssemblyInfoInputs.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.assets.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.csproj.AssemblyReference.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.csproj.CopyComplete";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.csproj.CoreCompileInputs.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.csproj.FileListAbsolute.txt";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.GeneratedMSBuildEditorConfig.editorconfig";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.genruntimeconfig.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.pdb";
            yield return "C:\\Source\\AzureStorageAutoBackup\\src\\obj\\Debug\\net5.0\\ref\\AzureStorageAutoBackup.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\AzureStorageAutoBackup.Tests.csproj";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\FilesBuilderTests.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\Testconfiguration.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.deps.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.exe";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.pdb";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.runtimeconfig.dev.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.runtimeconfig.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.deps.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.pdb";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.runtimeconfig.dev.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.runtimeconfig.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\CoverletSourceRootsMapping";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\FluentAssertions.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.Extensions.DependencyInjection.Abstractions.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.Extensions.Options.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.Extensions.Primitives.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.TestPlatform.AdapterUtilities.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.TestPlatform.CommunicationUtilities.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.TestPlatform.CoreUtilities.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.TestPlatform.CrossPlatEngine.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.TestPlatform.PlatformAbstractions.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.TestPlatform.Utilities.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.VisualStudio.CodeCoverage.Shim.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.VisualStudio.TestPlatform.Common.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.VisualStudio.TestPlatform.TestFramework.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\MoreLinq.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\Newtonsoft.Json.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\NuGet.Frameworks.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\System.Configuration.ConfigurationManager.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\System.Security.Cryptography.ProtectedData.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\testhost.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\testhost.exe";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\cs\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\cs\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\cs\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\cs\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\cs\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\de\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\de\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\de\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\de\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\de\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\de\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\de\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\de\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\es\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\es\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\es\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\es\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\es\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\fr\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\fr\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\fr\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\fr\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\fr\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\it\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\it\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\it\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\it\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\it\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ja\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ja\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ja\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ja\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ja\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ko\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ko\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ko\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ko\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ko\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pl\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pl\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pl\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pl\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pl\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pt-BR\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pt-BR\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pt-BR\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pt-BR\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\pt-BR\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ref\\AzureStorageAutoBackup.Tests.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ru\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ru\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ru\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ru\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\ru\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\runtimes\\win\\lib\\netstandard2.0\\System.Security.Cryptography.ProtectedData.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\tr\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\tr\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\tr\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\tr\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\tr\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hans\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hans\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hans\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hans\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hans\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hant\\Microsoft.TestPlatform.CommunicationUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hant\\Microsoft.TestPlatform.CoreUtilities.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hant\\Microsoft.TestPlatform.CrossPlatEngine.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hant\\Microsoft.VisualStudio.TestPlatform.Common.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\bin\\Debug\\net5.0\\zh-Hant\\Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\AzureStorageAutoBackup.Tests.csproj.nuget.dgspec.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\AzureStorageAutoBackup.Tests.csproj.nuget.g.props";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\AzureStorageAutoBackup.Tests.csproj.nuget.g.targets";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\project.assets.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\project.nuget.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\.NETCoreApp,Version=v5.0.AssemblyAttributes.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.AssemblyInfo.cs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.AssemblyInfoInputs.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.assets.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.csproj.AssemblyReference.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.csproj.CopyComplete";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.csproj.CoreCompileInputs.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.csproj.FileListAbsolute.txt";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.GeneratedMSBuildEditorConfig.editorconfig";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.genruntimeconfig.cache";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\AzureStorageAutoBackup.Tests.pdb";
            yield return "C:\\Source\\AzureStorageAutoBackup\\tests\\AzureStorageAutoBackup.Tests\\obj\\Debug\\net5.0\\ref\\AzureStorageAutoBackup.Tests.dll";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.gitignore";
            yield return "C:\\Source\\AzureStorageAutoBackup\\LICENSE";
            yield return "C:\\Source\\AzureStorageAutoBackup\\README.md";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\config";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\description";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\HEAD";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\index";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\packed-refs";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\applypatch-msg.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\commit-msg.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\fsmonitor-watchman.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\post-update.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\pre-applypatch.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\pre-commit.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\pre-merge-commit.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\pre-push.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\pre-rebase.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\pre-receive.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\prepare-commit-msg.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\push-to-checkout.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\hooks\\update.sample";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\info\\exclude";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\logs\\HEAD";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\logs\\refs\\heads\\main";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\logs\\refs\\remotes\\origin\\HEAD";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\objects\\pack\\pack-2f861ba61fb6c9b6190eb4f25fb3aa33b03d66e5.idx";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\objects\\pack\\pack-2f861ba61fb6c9b6190eb4f25fb3aa33b03d66e5.pack";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\refs\\heads\\main";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.git\\refs\\remotes\\origin\\HEAD";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.vscode\\launch.json";
            yield return "C:\\Source\\AzureStorageAutoBackup\\.vscode\\tasks.json";
        }
    }
}
